//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResearchGate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int TagID { get; set; }
        public Nullable<int> AuthID { get; set; }
        public Nullable<int> PapID { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Paper Paper { get; set; }
    }
}
